# Generated by Django 5.0.3 on 2024-03-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_documents_author_alter_medication_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='type',
            field=models.CharField(choices=[('prescription', 'Prescription'), ('lab_report', 'Lab Report'), ('scans', 'Scans'), ('medical_certificate', 'Medical Certificate')], default='prescription', max_length=20),
        ),
    ]
