# Generated by Django 5.0.3 on 2024-03-18 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_documents_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patientuser',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='patientuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='patientuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='patientuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='patientuser',
            name='user',
        ),
    ]
