# Generated by Django 5.0.3 on 2024-03-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='working_days',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=200),
        ),
    ]
