# Generated by Django 5.0.3 on 2024-03-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_alter_profile_working_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='working_days',
        ),
        migrations.AddField(
            model_name='profile',
            name='working_days',
            field=models.ManyToManyField(to='doctors.day'),
        ),
    ]
